services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: symfony-graphql-php
    volumes:
      - ./:/var/www/html:cached
    environment:
      APP_ENV: dev
      PHP_IDE_CONFIG: serverName=symfony
    depends_on:
      - db

  nginx:
    image: nginx:1.27-alpine
    container_name: symfony-graphql-nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  db:
    image: postgres:16-alpine
    container_name: symfony-graphql-db
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Optional DB UI
  adminer:
    image: adminer:4
    container_name: symfony-graphql-adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pgdata:
  symfony_vendor:
